version: '3.8'
services:
  # MySQL Service
  mysql_master:
    image: mysql:latest
    env_file:
      - ./mysql_master.env
    container_name: mysql_master
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql_master.cnf:/etc/mysql/my.cnf
    networks:
      - mysql

networks:
  mysql:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
